language: python
dist: xenial
sudo: True

python:
  - 3.9

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp .env.example .env

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov
  - cp .env.example .env

after_success:
  - pipenv run codecov
