# Generated by Django 3.2.9 on 2021-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
