# Generated by Django 3.2.9 on 2021-11-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_module_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('vimeo_id', models.CharField(max_length=32)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modules.module')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
